---
#
# Ansible tasks for the consul role
#

- name: Ensure standard consul ACLs are present
  run_once: true
  no_log: true
  uri:
    url: "{{ consul_base_url }}/v1/acl/update"
    method: PUT
    status_code: 200
    validate_certs: "{{ consul_api_validate_certs | default(false) }}"
    headers:
      X-Consul-Token: "{{ consul_acl_master_token | default(omit) }}"
    body: "{{ item.payload }}"
    body_format: json
  register: acl_debug
  with_items: "{{ consul_acl_rules | default([]) }}"
