---
#
# Ansible tasks for the consul role
#
# Notes:
#   - dhclient.conf (and similar) checks probably won't work on
#     RedHat family systems 7 and newer.

- name: Ensure dependencies are installed
  yum:
    name: "{{ item }}"
    state: installed
  with_items:
    - dnsmasq

# The 169.254.1.1 address (dummy0 interface) is key to getting containers access to dnsmasq.
- name: Configure dnsmasq listen addresses
  lineinfile:
    dest: /etc/dnsmasq.conf
    line: "listen-address={{ item }}"
    state: present
  with_items:
    - 169.254.1.1
    - 127.0.0.1
    - ::1
  notify:
    - Restart dnsmasq

- name: Configure dnsmasq cache-size
  lineinfile:
    dest: /etc/dnsmasq.conf
    line: "cache-size=1000"
    state: present
  notify:
    - Restart dnsmasq

- name: Configure dnsmasq to use a config directory
  lineinfile:
    dest: /etc/dnsmasq.conf
    regexp: "^#?conf-dir="
    line: "conf-dir=/etc/dnsmasq.d"
    state: present
  notify:
    - Restart dnsmasq

# WARNING: DNS issues observed when using 0.0.0.0 for consul_addresses_dns.
- name: Add localhost nameserver to resolv.conf
  lineinfile:
    dest: /etc/resolv.conf
    line: 'nameserver {{ consul_addresses_dns }}'
    insertbefore: "^nameserver"
    state: present

# dhclient.conf is created if it does not exist and should work
# for CentOS7 distributions
- name: Ensure dhclient maintains the localhost nameserver
  lineinfile:
    dest: /etc/dhcp/dhclient.conf
    line: 'prepend domain-name-servers {{ consul_addresses_dns }};'
    state: present
    create: yes

# @TODO See if this is still used (July 2016)
- name: Detect dhclient-eth0.conf
  stat:
    path: /etc/dhcp/dhclient-eth0.conf
  register: dh0

# @TODO See if this is still used (July 2016)
- name: Ensure dhclient maintains the localhost nameserver (eth0)
  lineinfile:
    dest: /etc/dhcp/dhclient-eth0.conf
    line: 'prepend domain-name-servers {{ consul_addresses_dns }};'
    state: present
  when: dh0.stat.exists

- name: Delegate consul DNS requests to the consul DNS port
  copy:
    dest: /etc/dnsmasq.d/10-consul
    content: |
      server=/{{ consul_domain }}/{{ consul_addresses_dns }}#{{ consul_port_dns }}
  notify:
    - Restart dnsmasq

- name: Ensure dnsmasq is started and enabled
  service:
    name: dnsmasq
    enabled: yes
    state: started
  become: yes
