---
#
# Ansible tasks for the consul role
#

- include: consul.yml
  tags:
    - consul

- include: dnsmasq.yml
  when: >
    consul_install_dnsmasq == true
  tags:
    - consul
    - consul_dns

# consul_acl_enabled is cast to boolean here since it is commonly
# passed via extra vars during cluster bootstrapping.
- include: consul-acl.yml
  when: >
    ( consul_acl_enabled | default(true) | bool ) and
    consul_acl_rules is defined
  tags:
    - consul
    - consul_acl

- include: consul-ui.yml
  when: >
    consul_install_ui == true
  tags:
    - consul
    - consul_ui
